### ISSUE TITLE
This is a really good initiative. I wonder why Mozilla's common voice platform is not considered.

### ISSUE THREAD

**Issue by freakeinstein** [smc/msc#2]
Hi, I find this a really good initiative from SMC. I have one question in mind - why the Mozilla Common Voice project for Malayalam language is not considered? Is there any licensing or technical difficulties there? Just being curious.

**Comment by santhoshtr** [comment]
Mozilla common voice is CC0(ppublic domain), the text corpus also need to be in public domain. To start a new language 5000 public domain sentences are needed. For Malayalam, it was very difficult to source that much public domain content. We do have public domain content but that is copyright expired content from a centuary back. The malayalam in those years does not represent our current day Malayalam.

On the otherhand, we have plenty of CC licensed content. Plus we wanted crowdsourcing that is optimized with smartphones where recording quality is so high compared to desktops. Flexibitliy to upload text corpus and extract audio helps us to fastly bootstrap a speech corpus - in CC by SA license.

**Comment by santhoshtr** [comment]
Documented at https://msc.smc.org.in/faq
